version: '2'

services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - default
networks:
  default:
    external:
      name: web_network